version: "3"

services:
  mysql:
    image: mysql:5.7
    # connects local db to my sql container
    volumes:
      #- ./db:/docker-entrypoint-initdb.d
      - ./db/1-wp-db.sql:/docker-entrypoint-initdb.d/1-wp-db.sql
    #   - ./db/2-migrate.sql:/docker-entrypoint-initdb.d/2-migrate.sql
    restart: always
    environment:
      MYSQL_DATABASE: purnellj_WPMRL
      MYSQL_USER: purnellj_WPMRL
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8082:80"
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite

  wordpress:
    image: wordpress
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
      # - ./src/wp-config.php:/var/www/html/wp-config.php
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_NAME: purnellj_WPMRL
      WORDPRESS_DB_USER: purnellj_WPMRL
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_TABLE_PREFIX: C5N_
    networks:
      - wpsite
networks:
  wpsite:
